
spring:
  cloud:
    gateway:
      routes:
      - id: conversionms
        uri: lb://conversionms
        predicates:
        - Path=/convfactor/**
      - id: currencyms
        uri: lb://currencyms
        predicates:
        - Path=/convertcurrency/**